[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_DISABLE_LIGHTNINGCSS = "1"
  TAILWIND_DISABLE_OXIDE = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
